version: '3'
services:
  app:
    container_name: homepage
    image: library/ruby
    volumes:
      - ../:/srv/
    ports:
      - 4567:4567
    environment:
      - TZ=Asia/Tokyo
    tty: true
    command: bash
    working_dir: /srv
